### PR TITLE
updates for today to changelogs

### PR DESCRIPTION
**Pull request by Tpelaaja**
updated the changelog

### CODE REVIEW

**Comment by vtheskeleton** [comment]
nonononono changelog is only for the app updates

**Comment by FemboyNova** [comment]
bread

**Comment by Tpelaaja** [comment]
ah im an idiot

**Comment by vtheskeleton** [comment]
vukky why reopen

**Comment by Vukkyy** [comment]
but we have the xmrig update in there no? @vtheskeleton

**Comment by Tpelaaja** [comment]
idfk

**Comment by FemboyNova** [comment]
because bread

**Comment by vtheskeleton** [comment]
that doesnt belong there either

**Comment by FemboyNova** [comment]
bread
go
brr also salad bind is qt

**Comment by Tpelaaja** [comment]
so this was closed & reopened. what

**Comment by vtheskeleton** [comment]
nobody can see the current changelog right? 
I thought it was just placeholders

**Comment by Vukkyy** [comment]
yeah nobody can see the current changelog, i just decided to put stuff there so we don't have to later

**Comment by Tpelaaja** [comment]
Lemme quickly go check

**Comment by Tpelaaja** [comment]
yeah k

**Pull request closed without merging**
