### PR TITLE
CPU mining with XMrig

### PR DESCRIPTION
**Pull request by memedmusic**
Title says all you need to know basically.
Unlike other miners, if this pr is submitted you will need to update your saladbind to see xmrig appear.

Everytime you click start mining saladbind fetches the latest miners and pools from the github repository. To test that xmrig worked I just used a local http server.

### CODE REVIEW

**Comment by TheBlueBurger** [comment]
You did the weird formatting thing again

**Comment by memedmusic** [comment]
> You did the weird formatting thing again

wdym? all the indentations are tabs

**Comment by Vukkyy** [comment]
yoo WHAT HAHAHAHA

**Comment by JovannMC** [comment]
people can finally stop complaining that there is no cpu mining if this is approved and merged

**Review by Vukkyy — APPROVED** [review]
skelly isn't answering me so idc anymore

**Pull request merged**
