### PR TITLE
Update node-fetch to 3.0.0

### PR DESCRIPTION
**Pull request by vtheskeleton**

### CODE REVIEW

**Review by Vukkyy — CHANGES_REQUESTED** [review]
this is... all in all, a very dogshit way to do it compared to just switching to ESM
i'd rather *not*

**Comment by vtheskeleton** [comment]
its what node-fetch docs says lol

**Comment by TheBlueBurger** [comment]
We could just add `"type": "module"` in the package.json and use a proper import statement

**Comment by vtheskeleton** [comment]
Just to be clear, this is not the best way possible to do it and if someone feels like it go ahead and nuke this pr and do it better

**Comment by TheBlueBurger** [comment]
I can try improving this later today

**Comment by vtheskeleton** [comment]
This is going nowhere, closing

**Pull request closed without merging**
