### PR TITLE
Setup.js has now a guide

### PR DESCRIPTION
**Pull request by Tpelaaja**
remade the fork as it had some problems idk.

Yeah, it has now a link for a guide.

If you need a bit.ly link ill be happy to switch to them and is more user friendly

### CODE REVIEW

**Comment by TheBlueBurger** [comment]
The failing test is a broken test

**Comment by Tpelaaja** [comment]
coolio

**Comment by Tpelaaja** [comment]
also labeler is shit

**Review by vtheskeleton — CHANGES_REQUESTED** [review]
https://bit.ly/saladbindconfig

**Comment by Tpelaaja** [comment]
Yes ill fix it asap

**Comment by Tpelaaja** [comment]
fixed

**Review by vtheskeleton — APPROVED** [review]

**Pull request merged**
