### PR TITLE
Make discord RPC disconnect on exit

### PR DESCRIPTION
**Pull request by TheBlueBurger**
Solves a bug that causes Saladbind to be on the status even after its been closed

### CODE REVIEW

**Review by vtheskeleton — APPROVED** [review]
looks alright

**Comment by vtheskeleton** [comment]
CONFLICTING FILES

**Comment by TheBlueBurger** [comment]
1 second

**Comment by vtheskeleton** [comment]
DOES NOT LOOK ALRIGHT

**Comment by vtheskeleton** [comment]
ill fix it

**Review by vtheskeleton — CHANGES_REQUESTED** [review]
CONFLICT

**Comment by TheBlueBurger** [comment]
Resolved the conflict! Don't merge yet as i need to check if i messed up the conflict thing!!!!

**Comment by vtheskeleton** [comment]
mm comment once you hav checked

**Comment by TheBlueBurger** [comment]
This is impossible to make work, I've tried everything. I will be closing this

**Pull request closed without merging**
