### PR TITLE
Add back button

### PR DESCRIPTION
**Pull request by TheBlueBurger**

### CODE REVIEW

**Review by vtheskeleton — CHANGES_REQUESTED** [review]
This wont work, the options need to have a name and value
Also you should make the go back button stand out from the others

**Comment by TheBlueBurger** [comment]
> This wont work, the options need to have a name and value

It works on my machine, but I could add a value
> Also you should make the go back button stand out from the others

I'll make that

**Comment by TheBlueBurger** [comment]
Fixed

**Review by vtheskeleton — APPROVED** [review]
Looks okay

**Pull request merged**
