### PR TITLE
Revert "Add docs for Automatic Rig finder (logs)"

### PR DESCRIPTION
**Pull request by vtheskeleton**
Reverts VukkyLtd/SaladBind#10

### CODE REVIEW

**Comment by TheBlueBurger** [comment]
🤔

**Comment by TheBlueBurger** [comment]
Did i miss something?

**Comment by vtheskeleton** [comment]
my plan was to only merge your pr once its added to the main release

**Comment by vtheskeleton** [comment]
and i kinda fucked up here

**Comment by TheBlueBurger** [comment]
Then revert the revert when its released

**Pull request merged**
