### PR TITLE
Fix bug causing it to not work on mac

### PR DESCRIPTION
**Pull request by TheBlueBurger**

### CODE REVIEW

**Comment by TheBlueBurger** [comment]
Cant test because i dont have a mac

**Comment by Vukkyy** [comment]
image
i have a feeling this wouldn't work

**Comment by TheBlueBurger** [comment]
Pushed another commit, i confused ?? with ||

**Comment by Cozina397** [comment]
uhh so when i click start mining it say configuring your miner then it say No miners are available for your machine D:
what to do?
Screen Shot 2021-08-29 at 11 14 19

**Comment by TheBlueBurger** [comment]
> 
> 
> uhh so when i click start mining it say configuring your miner then it say No miners are available for your machine D:
> what to do?
> Screen Shot 2021-08-29 at 11 14 19

Are you using this PR?

**Comment by Vukkyy** [comment]
> > uhh so when i click start mining it say configuring your miner then it say No miners are available for your machine D:
> > what to do?
> > Screen Shot 2021-08-29 at 11 14 19
> 
> Are you using this PR?

This PR changes command execution - how would it work with miner detection issues?

**Comment by TheBlueBurger** [comment]
> 
> 
> > > uhh so when i click start mining it say configuring your miner then it say No miners are available for your machine D:
> > > what to do?
> > > Screen Shot 2021-08-29 at 11 14 19
> > 
> > 
> > Are you using this PR?
> 
> This PR changes command execution - how would it work with miner detection issues?

True

**Comment by TheBlueBurger** [comment]
> 
> 
> uhh so when i click start mining it say configuring your miner then it say No miners are available for your machine D:
> what to do?
> Screen Shot 2021-08-29 at 11 14 19

Come to the discord since this isnt a problem with this pr

**Pull request merged**
