### PR TITLE
Make config better

### PR DESCRIPTION
**Pull request by TheBlueBurger**

### CODE REVIEW

**Comment by TheBlueBurger** [comment]
Ready for review?

**Comment by Vukkyy** [comment]
you tested that this works on compiled without bundling the compiler's config right?

**Comment by TheBlueBurger** [comment]
It shouldnt be different on compiled but I can test I guess

**Comment by TheBlueBurger** [comment]
Works now

**Comment by vtheskeleton** [comment]
While this is an interesting idea I dont see the benefit in doing this.
- It breaks other PRs
- Config is gotten for every single little thing
- Does not really improve anything as it works fine now
- Only real change here is how the code works

We decided the cons outweigh the pros and have chosen to not merge this

**Pull request closed without merging**
